name: Tom MacLean Music
favicon: null
layout_spectrum: 0
typography_spectrum: 0.73603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040309'
    - '#283dfa'
    - '#fbfefe'
    - '#f65e52'
    - '#6f91ff'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
