name: Tom MacLean Music
favicon: null
layout_spectrum: 0.49284074059687555
typography_spectrum: 0.45469015720300376
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5305775422602892
  lightness: 0.11095358082093298
  saturation: 0.47617711848579347
  rhythmicContrast: 0.008083731401711702
purpose: []
